baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sanchit Bansal'
theme = 'terminal'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Career"
    url = "/career/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 5

